Feature/pokemons
manaranjoc/pokemon-app pull request #1
Opened 2021-02-05 20:18 UTC by manaranjoc

Add functionality of listing pokemons, comparing them and filter them

2021-02-09 13:36 UTC, hackeo1 requested changes
- use single quotes in js files (including imports)
- use two space indentation

2021-02-09 13:36 UTC, hackeo1 commented on src/components/Navbar/Navbar.module.css
> +    background-color: whitesmoke;
- use css variables for the colors
- don't use named colors

2021-02-09 13:36 UTC, hackeo1 commented on src/components/Navbar/Navbar.module.css
> +    font-weight: bold;
use numbers for font weight (100, 200, 300, ..., 900)

2021-02-09 13:36 UTC, hackeo1 commented on src/components/Navbar/Navbar.module.css
> +.link a {
avoid styling tags, it is more maintainable to use classes

2021-02-09 13:36 UTC, hackeo1 commented on src/features/ItemList/Item.js
> +const URL_IMAGE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/'
all these environment constants must be in a single place (a single file) so they are easy to change

2021-02-09 13:36 UTC, hackeo1 commented on src/features/ItemList/actions.js
> +    });
the closing ) must be in the next line to align it with the opening one

2021-02-09 13:36 UTC, hackeo1 commented on src/features/ItemList/actions.js
> +export const filterItems = createAction('items/filter', function prepare(filterBy) {
use arrow functions instead of functions when possible

2021-02-09 13:36 UTC, hackeo1 commented on src/features/PokemonComparison/index.js
> +        if (e.target.id !== '') {
don't use single char variables

2021-02-09 13:36 UTC, hackeo1 commented on src/features/PokemonDetail/reducers.js
> +            console.log("Rejected")
don't leave developer logs in the final code, if this is a warning or error that the user is gonna suppose to see then there is an implementation left here.

2021-02-09 15:38 UTC, jugonz31 requested changes

2021-02-09 15:38 UTC, jugonz31 commented on src/API/itemAPI.js
> +const BASE_URL = 'https://pokeapi.co/api/v2/'
As mentioned by Carlos, I also suggest you have this in a single file. It would be even better if you check how to work with environment variables using Create React App.

2021-02-09 15:38 UTC, jugonz31 commented on src/features/ItemList/ItemList.module.css
> +    grid-template-columns: 1fr;
Try to use the same units (always rem, px, or fr but not all of them on different places)

2021-02-09 15:38 UTC, jugonz31 commented on src/features/PokemonComparison/index.js
> +            const ctx = chart.current.getContext('2d');
Use clear names for variables and constants, so any developer who eventually works on your projects will be able to understand the code more easily.

2021-02-15 13:26 UTC, hackeo1 requested changes
- use single quotes in imports
- use indentation of 2 spaces in css and js

2021-02-15 13:26 UTC, hackeo1 commented on src/API/itemAPI.js
> +import axios from "axios"
use single quotes

2021-02-15 13:26 UTC, hackeo1 commented on src/features/ItemList/index.js
> +            rootMargin: "30px",
use single quotes

2021-02-15 13:26 UTC, hackeo1 commented on src/features/PokemonDetail/PokemonDetail.module.css
> +    background-color: white;
don't use named colros

2021-02-15 14:06 UTC, hackeo1 requested changes
there are semicolons missing in different places on the app, I didn't notice before

2021-02-15 14:22 UTC, hackeo1 approved these changes

2021-02-18 15:23 UTC, merged